# Generated by Django 4.1.2 on 2022-10-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_car_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="location",
            field=models.CharField(default="Bergen", max_length=50),
            preserve_default=False,
        ),
    ]
