# Generated by Django 4.1.2 on 2022-10-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0005_user"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="Customer",),
    ]
