# Generated by Django 4.1.3 on 2022-11-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.car')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.customer')),
            ],
        ),
    ]
