# Generated by Django 4.1.3 on 2022-11-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_car_id_alter_customer_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
    ]
