# Generated by Django 4.1.3 on 2022-11-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_order_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='damaged',
            field=models.BooleanField(default=False),
        ),
    ]
