# Generated by Django 4.1.3 on 2022-11-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_car_damaged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='cid',
        ),
    ]
