# Generated by Django 4.1.3 on 2022-11-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_rename_id_car_cid_rename_cid_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='cid',
            new_name='id',
        ),
    ]
